# Generated by Django 4.2.11 on 2024-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_inventory_management_system_app', '0002_alter_brand_name_alter_color_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='founded_year',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
